---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/jekyll@d8081a80ce0003b82fc662944c69bb61db85e518 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "3.3"
