name: Build and Deploy
on:
    schedule:
        - 0 12 * * *
    push:
        branches:
            - release
    pull_request:
        branches:
            - release
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 2.7
                  bundler-cache: true

            - name: Install and Build
              run: |
                  JEKYLL_ENV=production bundle exec jekyll build --destination site

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site
                  publish_branch: master
                  user_name: Deployment Bot
                  user_email: deploy@travis-ci.org
