name: deploy

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/ruby/jekyll@f2d1998a2a659deaaa6a4e45beddc69388ed4894 # v0.22.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "3.2"
  
