---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/jekyll@af6eac3f165558bd83ebec41e0abfbe09a75817e # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "4.0"
