name: deploy

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/ruby/jekyll@a4f050199bd1fbb2d8fceebaa0278517c4992047 # v0.21.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "3.2"
  
