---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/jekyll@7a1cfa6fb4fcc2151803cb6f2cbbe6474dc7f860 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "4.0"
