---
name: Link Check Built Pages

on:
  schedule:
    - cron: 0 9 1 * *
  workflow_dispatch:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0
        with:
          branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lychee-args:
            --exclude 'https://scholar.google.com/citations\?user=.*'
            --no-progress --verbose .
