---
name: Link Check Built Pages

on:
  schedule:
    - cron: 0 9 1 * *
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@d8081a80ce0003b82fc662944c69bb61db85e518 # v0
        with:
          branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lychee-args:
            --exclude 'https://scholar.google.com/citations\?user=.*'
            --no-progress --verbose .
