---
name: Link Check Built Pages

on:
  schedule:
    - cron: 0 9 1 * *
  workflow_dispatch:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@0a54f965cd2ff530f3313bbbaf384cf54bbb7374 # v0
        with:
          branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lychee-args:
            --exclude 'https://scholar.google.com/citations\?user=.*'
            --no-progress --verbose .
