---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@cd920971be23f64c6174969604f86ea2e78718ba # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
