---
name: Link Check Source

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@d8081a80ce0003b82fc662944c69bb61db85e518 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lychee-args:
            --exclude '%7B%7B%20.*?' --exclude
            'https://scholar.google.com/citations\?user=.*' --no-progress
            --verbose .
