name: Linting

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@fcc1767c0a267471e0650c78600499bac965a061 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
