name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@d847296ec70e63ba26408f9b354de8a40ce2f006 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
