name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@19b19e930f3c18ea1a0317b831047b1c038e098a # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
