name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@7958ff821536746ea7a65cd1fa8737d05fa9b870 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
