---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@d7ef1ce76b6d02d7e81fe9bb3c22885c6376f986 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/vale@d7ef1ce76b6d02d7e81fe9bb3c22885c6376f986 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
