name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@cbc478d97e23dbb3ed95725817be6d84cef12b6c # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
