name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@e8328be8ba4a2d94e7ae9a9107c527be18de3073 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
