name: Linting

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@16317a64109e3a2f8351ec767bfad16bd78007c0 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
