name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@a5fa225f79b16f86bd36bbaf64d0efa9b5f6a78a # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
