name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@2875a6d0e8cde7569a844579e5528338cffae08f # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
