---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@2f931cd39ffb05f8f3a290179864e17ecd0845e4 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
