name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@0860bb5de5029a6ef6adbd1da9655eafc9c8231f # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
